version: '3.9'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo:/data/db
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    # ports:
    #   - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_LOCAL: mongodb://mongo:27017/Atelier_reviews
      PORT: 3000
    depends_on:
      - mongo

  dbseed:
      build:
        dockerfile: Dockerfile.dev
        context: ./data
      links:
        - mongo

  nginx:
    depends_on:
      - api
      - mongo
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
volumes:
  mongo: {}



